# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20170623_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='type',
            field=models.CharField(choices=[('follow', 'fl'), ('block', 'bl')], max_length=2),
        ),
    ]
