# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20170623_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='type',
            new_name='relation_type',
        ),
    ]
